### ISSUE TITLE
Revised kids signup form

### ISSUE THREAD

**Issue by NeilCFord** [adamamyl/jekylld-yrs2012#11]
The revised kids signup form needs to go live. This really needs to happen as soon as possible as we will be using it to sign up at least another 250 kids.

**Comment by adamamyl** [comment]
Presuming this is for https://github.com/lawrencejob/YRS-2012-CMS/commit/422fa6c9bc149269b62ddf23be3cbd0e9eb7da64 -- in which case, https://github.com/adamamyl/jekylld-yrs2012/commit/d3f5d70b8318c352c91e0aded4772f53704a8ec4 bodges this -- although it will break when the new signup form is renamed. There's no addressing of people using the previous version/URI (i.e. https://cms.yrs/signupperson), for which there should be a fix upstream.

**Comment by adamamyl** [comment]
(deployed, though)

**Comment by NeilCFord** [comment]
Thanks. 

Lawrence - could you work with Adam to resolve this please. Lets try an make it as elegant for people as possible.

Neil.

**Comment by lawrencejob** [comment]
(Thanks!) <-- Don't think it will be a problem - the old form still works fine. Don't understand why someone would access it with that URL anyway?
